"""
Django settings for bdOdonto project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from .python_mysql_dbconfig import read_db_config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o(ibdbquztox&4o#23fr&oflwxjugo&l%*7_0bp6&ppyb+73$p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'sistema_fichas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bdOdonto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bdOdonto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

od_db_config = read_db_config("config.ini", "mysql")
sigaa_disc_config = read_db_config("sigaa_disc_config.ini", "postgresql")
sigaa_users_config = read_db_config("sigaa_users_config.ini", "postgresql")
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': od_db_config['database'],
        'USER': od_db_config['user'],
        'PASSWORD': od_db_config['password'],
        'HOST': od_db_config['host'],
        'PORT': '3306',
    },
	'sigaa_disc':{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': sigaa_disc_config['database'],
        'USER': sigaa_disc_config['user'],
        'PASSWORD': sigaa_disc_config['password'],
        'HOST': sigaa_disc_config['host'],
        'PORT': sigaa_disc_config['port'],
    },
    'sigaa_users':{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': sigaa_users_config['database'],
        'USER': sigaa_users_config['user'],
        'PASSWORD': sigaa_users_config['password'],
        'HOST': sigaa_users_config['host'],
        'PORT': sigaa_users_config['port'],
    },
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

#LOGIN_URL default url (redirect url used by @login_required decorator)
LOGIN_URL = '/'
