# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Ficha',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='code',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='code',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='fichas',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo_ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_fichas.Tipo_Ficha'),
        ),
        migrations.DeleteModel(
            name='Tipo_Fichas',
        ),
        migrations.AddField(
            model_name='tipo_ficha',
            name='turma',
            field=models.ManyToManyField(to='sistema_fichas.Turma'),
        ),
    ]
