# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 15:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cel',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message="CEP deve estar no formato '64XXX-XXX'.", regex='^(64)\\d{3}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep_profissional',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="CEP deve estar no formato '64XXX-XXX'.", regex='^(64)\\d{3}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tel',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato '869XXXXXXXX'.", regex='^(86|89)(988|999|998|994|995|981)\\d{6}$')]),
        ),
    ]
