# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fichas', '0003_auto_20170907_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_dentistica',
            name='diag_risco_carie',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha_diagnostico',
            name='disc',
            field=models.CharField(choices=[('Estágio I', 'Estágio I'), ('Estágio II', 'Estágio II'), ('Estágio III', 'Estágio III'), ('EstágioIV', 'Estágio IV'), ('Outro', 'Outro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='corredor_bucal',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='degluticao',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Atípica', 'Atípica')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='doencas',
            field=models.CharField(choices=[('Não relata', 'Não relata'), ('Habituais', 'Habituais'), ('Outras', 'Outras')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='espessura',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='fonacao',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Atipica', 'Atípica')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='habitos',
            field=models.CharField(choices=[('Não relata', 'Não relata'), ('Sucção', 'Sucção'), ('Interposição labial', 'Interposição labial'), ('Interposição', 'Interposição'), ('Onicofagia', 'Onicofagia'), ('Outros', 'Outros')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='mandibula',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Prostruída', 'Prostruída'), ('Retruída', 'Retruída')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='maxila',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Prostruída', 'Prostruída'), ('Retruída', 'Retruída')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='perfil',
            field=models.CharField(choices=[('Reto', 'Reto'), ('Côncavo', 'Côncavo'), ('Convexo', 'Convexo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='posicao_labio_inferior',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Eversão', 'Eversão')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='qtd_gengiva_incisos',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='relacao_ls',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='sulco_mentolabial',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='tipo_facial',
            field=models.CharField(choices=[('Dolicofacial', 'Dolicofacial'), ('Mesofacial', 'Mesofacial'), ('Braquifacial', 'Braquifacial')], max_length=16),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='tonicidade_labial',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='tonicidade_mentoniano',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='vontade_correcao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sabe', 'Não sabe')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='zigomatico_frontal',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diminuído', 'Diminuído'), ('Aumentado', 'Aumentado')], max_length=15),
        ),
    ]
