# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fichas', '0003_auto_20170909_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cel',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep_profissional',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tel',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
