# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fichas', '0004_auto_20170907_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_dentistica',
            name='diag_risco_carie',
            field=models.CharField(choices=[(b'Alto', b'Alto'), (b'M\xe9dio', b'M\xe9dio'), (b'Baixo', b'Baixo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha_dentistica',
            name='horario_consumo_acucar',
            field=models.CharField(choices=[(b'Junto \xc3\xa0s refei\xc3\xa7\xc3\xb5es', b'Junto \xc3\xa0s refei\xc3\xa7\xc3\xb5es'), (b'Intervalos entre refei\xc3\xa7\xc3\xb5es', b'Intervalos entre refei\xc3\xa7\xc3\xb5es'), (b'Junto \xc3\xa0s refei\xc3\xa7\xc3\xb5es e nos intervalos das mesmas', b'Junto \xc3\xa0s refei\xc3\xa7\xc3\xb5es e nos intervalos das mesmas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha_diagnostico',
            name='disc',
            field=models.CharField(choices=[(b'Est\xe1gio I', b'Est\xe1gio I'), (b'Est\xe1gio II', b'Est\xe1gio II'), (b'Est\xe1gio III', b'Est\xe1gio III'), (b'Est\xe1gioIV', b'Est\xe1gio IV'), (b'Outro', b'Outro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='alergia',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='alteracoes_sanguineas',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='diabetes',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='doencas_cardiovasculares',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='em_tratamento_med',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='febre_reumatica',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='gravida',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='hepatite',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='hipertensao',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='marcapasso',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_endodontia',
            name='problemas_hemorragicos',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='arco_inferior',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Amplo', b'Amplo'), (b'Atr\xc3\xa9sico', b'Atr\xc3\xa9sico')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='arco_superior',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Amplo', b'Amplo'), (b'Atr\xc3\xa9sico', b'Atr\xc3\xa9sico')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='corredor_bucal',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='degluticao',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'At\xedpica', b'At\xedpica')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='dentadura',
            field=models.CharField(choices=[(b'Decidua', b'Dec\xc3\xaddua'), (b'Mista(1o Transit.)', b'Mista(1o Transit.)'), (b'Mista(2o Transit.)', b'Mista(2o Transit.)'), (b'Mista(Intertransit.)', b'Mista(Intertransit.)'), (b'Permanente', b'Permanente'), (b'Arco Tipo I', b'Arco Tipo I'), (b'Arco Tipo II', b'Arco Tipo II')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='diagnostico',
            field=models.CharField(choices=[(b'Oclus\xc3\xa3o normal', b'Oclus\xc3\xa3o normal'), (b'M\xc3\xa1 oclus\xc3\xa3o', b'M\xc3\xa1 oclus\xc3\xa3o')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='doencas',
            field=models.CharField(choices=[(b'N\xe3o relata', b'N\xe3o relata'), (b'Habituais', b'Habituais'), (b'Outras', b'Outras')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='espessura',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='fonacao',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Atipica', b'At\xedpica')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='habitos',
            field=models.CharField(choices=[(b'N\xe3o relata', b'N\xe3o relata'), (b'Suc\xe7\xe3o', b'Suc\xe7\xe3o'), (b'Interposi\xe7\xe3o labial', b'Interposi\xe7\xe3o labial'), (b'Interposi\xe7\xe3o', b'Interposi\xe7\xe3o'), (b'Onicofagia', b'Onicofagia'), (b'Outros', b'Outros')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='mandibula',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Prostru\xedda', b'Prostru\xedda'), (b'Retru\xedda', b'Retru\xedda')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='maxila',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Prostru\xedda', b'Prostru\xedda'), (b'Retru\xedda', b'Retru\xedda')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='perfil',
            field=models.CharField(choices=[(b'Reto', b'Reto'), (b'C\xf4ncavo', b'C\xf4ncavo'), (b'Convexo', b'Convexo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='posicao_labio_inferior',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Evers\xe3o', b'Evers\xe3o')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='qtd_gengiva_incisos',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='relacao_ls',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='sulco_mentolabial',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='tonicidade_labial',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='tonicidade_mentoniano',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='trespasse_vertical',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Aumentado', b'Aumentado'), (b'Topo', b'Topo'), (b'Mordida aberta', b'Mordida aberta'), (b'Dentoalveolar', b'Dentoalveolar'), (b'Esquel\xc3\xa9tica', b'Esquel\xc3\xa9tica')], max_length=17),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='vontade_correcao',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xe3o', b'N\xe3o'), (b'N\xe3o sabe', b'N\xe3o sabe')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_ortodontia',
            name='zigomatico_frontal',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Diminu\xeddo', b'Diminu\xeddo'), (b'Aumentado', b'Aumentado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='acamado',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='alergia_anestesia',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='alergia_antibioticos',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='alergia_aspirina',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='alergia_nao_medicamentos',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='alergia_sulfas',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='anemia',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='diabetes',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='doenca_infec',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='doencas_cardiovasculares',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='febre_reumatica',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='figado',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='gravida',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='hemorragia_extrac_dentes',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='inchaco_dor_juntas',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='operacao',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='problema_menstruacao',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='radioterapia',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='sangramento_excessivo',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='sangramento_gengiva',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='tonturas',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='tratamento_gengiva',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='tuberculose',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='ulcera',
            field=models.CharField(choices=[(b'Sim', b'Sim'), (b'N\xc3\xa3o', b'N\xc3\xa3o'), (b'N\xc3\xa3o sei', b'N\xc3\xa3o sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha_periodontia',
            name='variacao_peso',
            field=models.CharField(choices=[(b'Aumentou', b'Aumentou'), (b'Diminuiu', b'Diminuiu'), (b'Sem mudan\xc3\xa7as', b'Sem mudan\xc3\xa7as')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_urgencia',
            name='atend',
            field=models.CharField(choices=[(b'Est\xc3\xa1gio III', b'Est\xc3\xa1gio III'), (b'Est\xc3\xa1gio IV', b'Est\xc3\xa1gio IV'), (b'Outro', b'Outro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha_urgencia',
            name='especialidade',
            field=models.CharField(choices=[(b'Endodontia', b'Endodontia'), (b'Pr\xc3\xb3tese', b'Pr\xc3\xb3tese'), (b'Periodontia', b'Periodontia'), (b'Dent\xc3\xadstica', b'Dent\xc3\xadstica'), (b'Cirurgia', b'Cirurgia'), (b'Outro', b'Outro')], max_length=15),
        ),
    ]
