# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fichas', '0006_auto_20170910_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='pontos',
            field=models.TextField(blank=True),
        ),
    ]
